image: node:latest  # Use Node.js Docker image

stages:
  - build

before_script:
  - npm install -g @angular/cli  # Install Angular CLI globally
  - npm install  # Install project dependencies

build:
  stage: build
  script:
    - ng build --configuration=production  # Build the Angular app for production
  artifacts:
    paths:
      - dist/  # Save the built application as an artifact
