stages:
  - build

build:
  stage: build
  image: node:18
  before_script:
    - npm install -g @angular/cli
    - npm install --legacy-peer-deps
  script:
    - ls
    - npm ci --legacy-peer-deps
    - npm run build
  artifacts:
    name: "neocorp-ui"
    paths:
      - target/dist


  
    



    

