stages:
  - build

build:
  stage: build
  image: node:20.5.0-alpine
  before_script:
    - npm install -g @angular/cli
    - npm install --legacy-peer-deps
  script:
    - npm ci --legacy-peer-deps
    - ls
    - ng update @angular/cli @angular/core --allow-dirty --force
    - npm run build
  artifacts:
    name: "neocorp-ui"
    paths:
      - target/dist


  
    



    

