stages:
  - build

build-frontend:
  stage: build
  image: node:18
  before_script:
  - npm install -g @angular/cli  # Install Angular CLI globally
  - npm install  # Install project dependencies
  script:
    - ls
    - ng -v
 
