stages:
  - build
  - deploy

build-frontend:
  stage: build
  image: node:20.5.0-alpine

  script:
    - npm install --legacy-peer-deps
    - sed -i "/static Éµdir/c\ " node_modules/ngx-print/lib/ngx-print.directive.d.ts
    - npm run build
  artifacts:
    name: "dist-output"
    paths:
      - dist

deploy-frontend:
  stage: deploy
  image: alpine
  dependencies:
    - "build-frontend"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - mv dist neocrop
    - rm -rf /home/staginguser/public_html/neomaxer/neocorp
    - scp -o StrictHostKeyChecking=no ivycard-0.0.1-SNAPSHOT.jar $SERVER_USER@$SERVER_IP:/home/staginguser/public_html/neomaxer/
