stages:
  - build
  - deploy

build-frontend:
  stage: build
  image: node:20.5.0-alpine

  script:
    - npm install --legacy-peer-deps
    - sed -i "/static Éµdir/c\ " node_modules/ngx-print/lib/ngx-print.directive.d.ts
    - npm run build
  artifacts:
    name: "doneocards-jar-artifact"
    paths:
      - target/dist

deploy-frontend:
  stage: deploy
  image: alpine

  script:
    - ls
